#!/usr/bin/env bash

# Name: sharefolder
# Desc: 设置目录共享
# Date: 2020-04-16 by yongirl

clear

# Check if user is root
if [ $(id -u) != "0" ]; then
  echo "Error: You must be root to run this script."
  exit 1
fi

# Header prompt
echo "================================================================================"
echo "share folder"
echo "================================================================================"


# 安装需要的库
yum -y install kernel-devel
yum -y install bzip2
yum -y install gcc


#挂载 增强工具
mkdir /mnt/cdrom
mount /dev/cdrom /mnt/cdrom

#安装 增强工具
/mnt/cdrom/VBoxLinuxAdditions.run


#创建共享目录
mkdir /home/winshare

#创建服务文件
echo "[Unit]
Description=home winshare mount

[Mount]
What=winshare
Where=/home/winshare
Type=vboxsf
Options=defaults

[Install]
WantedBy=multi-user.target" > /usr/lib/systemd/system/home-winshare.mount


# 注册服务-设为自动启动
systemctl enable home-winshare.mount
systemctl start home-winshare.mount


echo "set ok"

exit 0
