version: '3.8'

networks:
  dev_network:

services:
  nginx:
    container_name: nginx
    image: yongirl320/nginx
    volumes:
      - /home/winshare/server/nginx:/home/volume
    networks:
      - dev_network
    ports:
      - "80:80"
      - "443:443"
  php7230-apache:
    container_name: php7230-apache
    image: yongirl320/php7230-apache
    volumes:
      - /home/winshare/server/www:/home/www
      - /home/winshare/server/httpd:/home/volume
    networks:
      - dev_network
    ports:
      - "8001:8001"
