version: '3.8'

networks:
  dev_network:

services:
  nginx:
    container_name: nginx
    image: 10.5.1.173:5000/nginx
    volumes:
      - /home/winshare/server/nginx:/home/volume
    networks:
      - dev_network
    ports:
      - "80:80"
      - "443:443"
  php7230-apache:
    container_name: php7230-apache
    image: 10.5.1.173:5000/php7230-apache
    volumes:
      - /home/winshare/server/www:/home/www
      - /home/winshare/server/httpd:/home/volume
    networks:
      - dev_network
    ports:
      - "8001:8001"
  php7317-apache:
    container_name: php7317-apache
    image: 10.5.1.173:5000/php7317-apache
    volumes:
      - /home/winshare/server/www:/home/www
      - /home/winshare/server/httpd:/home/volume
    networks:
      - dev_network
    ports:
      - "8002:8002"
  mariadb:
    container_name: mariadb
    image: 10.5.1.173:5000/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '!@#!@#'
    volumes:
      - /home/server/datadir/mariadb:/var/lib/mysql
    networks:
      - dev_network
    expose:
      - "3306"
  phpmyadmin:
    image: 10.5.1.173:5000/phpmyadmin
    container_name: 'phpmyadmin'
    environment:
      PMA_HOST: mariadb
    networks:
      - dev_network
    ports:
      - '8080:80'
  mongo:
    container_name: mongodb
    image: 10.5.1.173:5000/mongo
    #restart: always
    volumes:
      - /home/server/datadir/mongo/db:/data/db
      - /home/server/datadir/mongo/configdb:/data/configdb
    networks:
      - dev_network
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '!@#!@#'
  mongo-express:
    container_name: mongo-express
    image: 10.5.1.173:5000/mongo-express
    #restart: always
    networks:
      - dev_network
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: '!@#!@#'
